covid19_data_analysis_platform/covid/urls.py
from django.urls import path
from covid import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'covid'

urlpatterns = [
    path('', views.index, name='index'),
    path('analysis/', views.analysis, name='analysis'),
    path('prediction/', views.prediction, name='prediction'),
    path('dataframe/', views.dataframe, name='dataframe'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

covid19_data_analysis_platform/covid19_data_analysis_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from covid import views

urlpatterns = [
    path('', views.index, name='index'),
    path('covid/', include('covid.urls')),
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

covid19_data_analysis_platform/covid/models.py
from django.db import models

# Create your models here.

covid19_data_analysis_platform/covid/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    # return HttpResponse("Covid-19 Data Platform")
    context_dict = {}
    return render(request, 'index.html', context=context_dict)


def about(request):
    return render(request, 'about.html')


def info(request):
    return render(request, 'info.html')


def analysis(request):
    return render(request, 'covid/analysis.html')


def prediction(request):
    return render(request, 'covid/prediction.html')


def dataframe(request):
    return render(request, 'covid/dataframe.html')

covid19_data_analysis_platform/templates/about.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
About
{% endblock %}

{% block body_block %}
<section id="inner-title" class="inner-title">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-6"><h2>About us</h2></div>
      <div class="col-md-6 col-lg-6">
        <div class="breadcrumbs">
          <ul>
            <li>Current Page:</li>
            <li><a href="{% url 'index' %}">Homepage</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section> 
<section id="section18" class="section-margine">
  <div class="container">
  <div class="section18">
    <div class="row">
      <div class="col-md-8 col-lg-8 wow fadeInUp">
        <div class="textcont">
          <h3>Some Technical Information Here</h3>
          <p>Some Technical Information Here.<br><br></p>
{#          <p>aaa</p>#}
{#          <h4>header</h4>#}
{#          <p>bbb</p>#}
        </div>  
      </div>
      <div class="col-md-4 col-lg-4 wow fadeInUp" data-wow-delay=".2s">
        <div class="section-18-img">
{#          <img src="{% static 'images/a0.jpg' %}"  class="img-responsive" alt="">#}
        </div>
      </div>
    </div>
  </div>  
  </div>
</section>

<section id="section16" class="section16">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-md-offset-1">
        <div class="single-location">
          <div class="loc-icon">
            <i class="fa fa-phone fa-2x"></i>
          </div>
          <span class="loc-content">+44 752 999 7299</span>
{#          <span class="loc-content">+86 150 4056 9459</span>#}
        </div>
      </div>
      <div class="col-md-4">
        <div class="single-location">
          <div class="loc-icon">
            <i class="fa fa-envelope fa-2x"></i>
          </div>
          <span class="loc-content">wangyulinchris@gmail.com</span>
{#          <span class="loc-content">905946576@qq.com</span>#}
        </div>
      </div>
      <div class="col-md-3">
        <div class="single-location">
          <div class="loc-icon">
            <i class="fa fa-map-marker fa-2x"></i>
          </div>
          <span class="loc-content">107 Kelvinhaugh Street,</span>
          <span class="loc-content">Glasgow, G3 8PX</span>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

covid19_data_analysis_platform/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="A Data Analysis & Prediction Platform of COVID-19 Datasets Based on Machine Learning Algorithms">
<meta name="keywords" content="Pixel">
<meta name="author" content="Yulin Wang">
<!-- Site Title   -->
<title>
    {% block title_block %}{% endblock %}
</title>
<!-- Bootstrap -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-dropdownhover.min.css' %}" rel="stylesheet">
<!-- Fonts Awesome -->
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Raleway:400,200,300,100,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400" rel="stylesheet">
<!-- animate Effect -->
<link href="{% static 'css/animate.css' %}" rel="stylesheet">
<!-- Main CSS -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<!-- Responsive CSS -->
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
</head>
<body>
<header id="header" class="head">
  <div class="top-header">
     <div class="container">
       <div class="row ">
         <ul class="contact-detail2 col-md-6 pull-left">
           <li> <a href="#" target="_blank"><i class="fa fa-mobile"></i>Call Us + 44 752 999 7299</a> </li>
           <li> <a href="#" target="_blank"><i class="fa fa-envelope-o"></i> wangyulinchris@gmail.com</a> </li>
         </ul>
         <div class="social-links col-md-6 pull-right">
           <ul class="social-icons pull-right">
             <li> <a href="#" target="_blank"><i class="fa fa-facebook"></i></a> </li>
             <li> <a href="#" target="_blank"><i class="fa fa-twitter"></i></a> </li>
             <li> <a href="#" target="_blank"><i class="fa fa-instagram"></i></a> </li>
             <li> <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a> </li>
{#             <li> <a href="#" target="_blank"><i class="fa fa-pinterest"></i></a> </li>#}
             <li> <a href="#" target="_blank"><i class="fa fa-skype"></i></a> </li>
{#             <li> <a href="#" target="_blank"><i class="fa fa-dribbble"></i></a> </li>#}
           </ul>
         </div>
       </div>
     </div>
    </div>
    <nav class="navbar navbar-default navbar-menu">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">
            <div class="logo-text"><span><samp>C</samp>COVID-19</span> Data Platform</div>
            <!-- <img src="{% static 'images/logo.png' %}" alt="logo"> -->
          </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" data-hover="dropdown" data-animations="fadeIn">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'index' %}">Homepage</a></li>
            <li><a href="{% url 'covid:analysis' %}">Analysis</a></li>
            <li><a href="{% url 'covid:prediction' %}">Prediction</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
{#            <li><a href="{% url 'info' %}">Info</a></li>#}
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </nav>
</header>

{% block body_block %}

{% endblock %}

<section id="section8" class="mytestimonial">
  <div class="container">
    <div class="row">
      <div data-ride="carousel" class="carousel slide" id="testimonial">
        <ol class="carousel-indicators">
          <li data-target="#testimonial" data-slide-to="0" class="active"><img alt="Testimonial" class="img-responsive" src="{% static 'images/people/1.jpg' %}">
          </li>
          <li data-target="#testimonial" data-slide-to="1"><img alt="Testimonial" class="img-responsive" src="{% static 'images/people/2.jpg' %}">
          </li>
        </ol>
        <div class="carousel-inner">
          <div class="item text-center quotes-detail active left">
            <p class="client-quote"><i class="fa fa-quote-left"></i>
              But vaccines alone will not end this pandemic. We have many other tools to stop transmission and save lives: effective public health tools, and effective medical tools. We must use them all.
            <i class="fa fa-quote-right "></i></p>
            <h5 class="client-name">Dr Tedros Adhanom (Director-General of WHO)</h5>
          </div>
          <div class="item text-center quotes-detail next left">
            <p class="client-quote"><i class="fa fa-quote-left "></i>
              Once you've vaccinated you have a feeling of you're protected. It's difficult for people if they've never had a vaccine, but they ought to think about other people rather than themselves.
            <i class="fa fa-quote-right "></i></p>
            <h5 class="client-name">Queen Elizabeth II</h5>
          </div>
        </div> <!-- end carosel-inner -->
      </div> <!-- end Quotes -->
    </div>
  </div>
</section>
<section id="section9" class="section-9-background">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-sm-4 col-xs-6"><img src="{% static 'images/clients/1.png' %}" class="img-responsive wow fadeInUp" alt=""></div>
      <div class="col-md-2 col-sm-4 col-xs-6"><img src="{% static 'images/clients/2.png' %}" class="img-responsive wow fadeInUp" alt=""></div>
      <div class="col-md-2 col-sm-4 col-xs-6"><img src="{% static 'images/clients/3.png' %}" class="img-responsive wow fadeInUp" alt=""></div>
      <div class="col-md-2 col-sm-4 col-xs-6"><img src="{% static 'images/clients/4.png' %}" class="img-responsive wow fadeInUp" alt=""></div>
      <div class="col-md-2 col-sm-4 col-xs-6"><img src="{% static 'images/clients/5.png' %}" class="img-responsive wow fadeInUp" alt=""></div>
      <div class="col-md-2 col-sm-4 col-xs-6"><img src="{% static 'images/clients/6.png' %}" class="img-responsive wow fadeInUp" alt=""></div>
    </div>
  </div>
</section>

<section id="footer-top" class="footer-top">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-lg-3">
        <div class="footer-top-box">
          <h4>About Us</h4>
          <p>Author: Yulin Wang<br>
             Student ID: 2559241</p>
        </div>
{#        <div class="footer-top-box">#}
{#          <h4>Office Hour</h4>#}
{#          <b>Mon-Fri :</b> 09am to 06pm<br/>#}
{#          <b>Tues-Wed :</b> Special Appointment#}
{#        </div>#}
      </div>
      <div class="col-md-3 col-lg-3">
{#        <div class="footer-top-box">#}
{#          <h4>About Us</h4>#}
{#          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text</p>#}
{#        </div>#}
        <div class="footer-top-box">
          <h4>Data Sources</h4>
            <b>COVID-19 data from John Hopkins University</b>
            <b>https://www.kaggle.com/antgoldbloom/covid19-data-from-john-hopkins-university</b>
{#          <b>Mon-Fri :</b> 09am to 06pm<br/>#}
{#          <b>Tues-Wed :</b> Special Appointment#}
        </div>
      </div>
      <div class="col-md-3 col-lg-3">
        <div class="footer-top-box">
          <h4>Latest News</h4>
          <ul>
            <li>
              <div class="recent-post-widget">
                <a href="#" class="widget-img-thumb">
                  <img src="{% static 'images/post-1.jpg' %}" class="img-responsive">
                </a>
                <div class="widget-content">
                  <h5><a href="#" class="sidebar-item-title">News 1</a></h5>
                  <a href="#">
                    <p class="widget-date">Posted: xxx days ago</p>
                  </a>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
            <li>
              <div class="recent-post-widget">
                <a href="#" class="widget-img-thumb">
                  <img src="{% static 'images/post-2.jpg' %}" class="img-responsive">
                </a>
                <div class="widget-content">
                  <h5><a href="#" class="sidebar-item-title">News 2</a></h5>
                  <a href="#">
                    <p class="widget-date">Posted: xxx days ago</p>
                  </a>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-md-3 col-lg-3">
        <div class="footer-top-box">
          <h4>Contact us</h4>
          <p><b>Location : University of Glasgow,</b> Glasgow, UK<br/>
            <b>Phone: </b> +44 7529997299<br/>
            <b>Email: </b> wangyulinchris@gmail.com </p>
        </div>
{#        <div class="footer-top-box">#}
{#          <h4>Subscribe</h4>#}
{#          <div class="cs-form">#}
{#            <form action="#" method="post">#}
{#              <div class="input-holder">#}
{#                <input type="email" placeholder="Enter Valid Email Address">#}
{#                <label> <i class="fa fa-location-arrow fa-2x"></i>#}
{#                  <input class="submit-bgcolor" type="submit" value="submit">#}
{#                </label>#}
{#              </div>#}
{#            </form>#}
{#          </div>#}
{#        </div>#}
      </div>
    </div>
  </div>
</section>
<section id="footer-bottom" class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-lg-9">
{#        <div class="copyright">Copyright &copy; 2021.Company name All rights reserved.</div>#}
      </div>
      <div class="col-lg-3">
        <ul class="list-inline social-buttons">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-instagram"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-skype"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.plugin.min.js' %}"></script>
<script src="{% static 'js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/bootstrap-dropdownhover.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

covid19_data_analysis_platform/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
Homepage
{% endblock %}

{% block body_block %}
<section id="slider" class="" xmlns="http://www.w3.org/1999/html">
  <!-- Carousel -->
  <div id="main-slide" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ol class="carousel-indicators visible-lg visible-md">
        <li data-target="#main-slide" data-slide-to="0" class="active"></li>
       <li data-target="#main-slide" data-slide-to="1"></li>
       <li data-target="#main-slide" data-slide-to="2"></li>
    </ol><!--/ Indicators end-->

    <!-- Carousel inner -->
    <div class="carousel-inner">

      <div class="item active" style="background-image:url({% static 'images/slide/1.jpg' %})">
            <div class="slider-content text-left">
               <div class="col-md-12">
                   <h2 class="slide-title effect2">Latest COVID-19 Data Here</h2>
                   <h3 class="slide-sub-title effect3">Latest Data</h3>
                   <p class="slider-description lead effect3">Check the latest COVID-19 daily data here.<br>Dataset downloading is also available.</p>
                   <p class="effect3">
                    <a href="{% url 'covid:dataframe' %}" class="slider btn btn-primary">Check up Data</a>
                    <a href="https://www.kaggle.com/antgoldbloom/covid19-data-from-john-hopkins-university/download" class="slider btn btn-secondary">Download Data</a>
                   </p>      
               </div>
            </div>
       </div><!--/ Carousel item 1 end -->


      <div class="item" style="background-image:url({% static 'images/slide/2.jpg' %})">
            <div class="slider-content">
               <div class="col-md-12 text-center">
                   <h2 class="slide-title effect4">Visualised Data Analysis Here</h2>
                   <h3 class="slide-sub-title effect5">Data Analysis</h3>
                   <p>
                    <a href="{% url 'covid:analysis' %}" class="slider btn btn-primary">Analysis</a>
                   </p>      
               </div>
            </div>
       </div><!--/ Carousel item 2 end -->


       <div class="item" style="background-image:url({% static 'images/slide/3.jpg' %})">
            <div class="slider-content text-right">
               <div class="col-md-12">
                   <h2 class="slide-title effect6">Future Data Prediction Here</h2>
                   <h3 class="slide-sub-title effect7">Prediction</h3>
                   <p class="slider-description lead effect7">Check the reasonable new cases predictions here.<br>See the possible trend in the next 10 days.</p>
                   <p>
                    <a href="{% url 'covid:prediction' %}" class="slider btn btn-primary">Prediction</a>
                    <a href="{% url 'about' %}" class="slider btn btn-primary border">Know More</a>
                   </p>      
               </div>
            </div>
        </div><!--/ Carousel item 3 end -->
        
    </div><!-- Carousel inner end-->

    <!-- Controllers -->
    <a class="left carousel-control" href="#main-slide" data-slide="prev">
        <span><i class="fa fa-angle-left"></i></span>
    </a>
    <a class="right carousel-control" href="#main-slide" data-slide="next">
        <span><i class="fa fa-angle-right"></i></span>
    </a>
  </div><!--/ Carousel end -->
</section>

<section id="section1" class="section-margine">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="section-1-box wow bounceIn">
          <div class="section-1-box-icon-background"><i class="fa fa-ambulance fa-2x"></i></div>
          <h4 class="text-center">US</h4>
          <p class="text-center">New Cases: <br> 34330 <br> New Deaths: <br> 382 </p>
        </div>
      </div>
      <div class="col-md-3  col-sm-6">
        <div class="section-1-box wow bounceIn" data-wow-delay=".1s">
          <div class="section-1-box-icon-background"><i class="fa fa-user-md fa-2x"></i></div>
          <h4 class="text-center">UK</h4>
          <p class="text-center">New Cases: <br> 46654 <br> New Deaths: <br> 147 </p>
        </div>
      </div>
      <div class="col-md-3  col-sm-6">
        <div class="section-1-box wow bounceIn" data-wow-delay=".2s">
          <div class="section-1-box-icon-background"><i class="fa fa-h-square fa-2x"></i></div>
          <h4 class="text-center">India</h4>
          <p class="text-center">New Cases: <br> 9119 <br> New Deaths: <br> 396 </p>
        </div>
      </div>
      <div class="col-md-3  col-sm-6">
        <div class="section-1-box wow bounceIn" data-wow-delay=".3s">
          <div class="section-1-box-icon-background"><i class="fa fa fa-heartbeat fa-2x"></i></div>
          <h4 class="text-center">Brazil</h4>
          <p class="text-center">New Cases: <br> 12126 <br> New Deaths: <br> 303 </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="section3" class="section-margine section3-background">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="section-3-box">
          <figure><i class="fa fa-desktop fa-2x"></i></figure>
          <h3><span class="counter">577,368</span></h3>
          <h4>New Cases</h4>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="section-3-box">
          <figure><i class="fa fa-group fa-2x"></i></figure>
          <h3><span class="counter">260,580,001</span></h3>
          <h4>Total Cases</h4>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="section-3-box">
          <figure><i class="fa fa-coffee fa-2x"></i></figure>
          <h3><span class="counter">7,154</span></h3>
          <h4>New Deaths</h4>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="section-3-box">
          <figure><i class="fa fa-glass fa-2x"></i></figure>
          <h3><span class="counter">5,203,535</span></h3>
          <h4>Total Deaths</h4>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="section4" class="section-4 section-margine">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <header class="title-head">
          <h2>Some Tips Here</h2>
          <p>Some tips here to help you get rid of infection with COVID-19.</p>
          <div class="line-heading">
            <span class="line-left"></span>
            <span class="line-middle">+</span>
            <span class="line-right"></span>
          </div>
        </header>
      </div>
      <div class="col-md-4 col-sm-6 right wow fadeInUp">
        <ul class="section">
          <li class="left"><i class="fa fa-medkit"></i></li>
          <li><strong>Face Coverings</strong>
          <p>Put on your face covering.<br>Cover your nose and mouth.</p>
          <a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public/when-and-how-to-use-masks" class="btn btn-primary btn-sm">Know More</a>
        </ul>
        <ul class="section two">
          <li class="left"><i class="fa fa-stethoscope"></i></li>
          <li><strong>Washing Hands</strong>
            <p>Wash your hands frequently.<br>More than 20 seconds every time.</p>
            <a href="https://www.who.int/gpsc/5may/Hand_Hygiene_Why_How_and_When_Brochure.pdf" class="btn btn-primary btn-sm">Know More</a>
          </li>
        </ul>
      </div>
      <div class="col-md-4 hidden-sm hidden-xs left wow fadeInUp" data-wow-delay=".2s"><img alt="" src="{% static 'images/m4.png' %}"></div>
      <!-- end left -->
      <div class="col-md-4 col-sm-6 right wow fadeInUp" data-wow-delay=".3s">
        <ul class="section three">
          <li class="left"><i class="fa fa-user-md"></i></li>
          <li><strong>Social Distance</strong>
            <p>Keep social distance in public areas.<br>More than 1 meter is recommended.</p>
            <a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019/question-and-answers-hub/q-a-detail/coronavirus-disease-covid-19-small-public-gatherings" class="btn btn-primary btn-sm">Know More</a>
          </li>
        </ul>
        <ul class="section four">
          <li class="left"><i class="fa fa-unlink"></i></li>
          <li><strong>Getting Vaccinated</strong>
            <p>Fully vaccinated can protect your health.<br>Get your booster if possible.</p>
            <a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019/covid-19-vaccines/advice" class="btn btn-primary btn-sm">Know More</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

{% endblock %}

covid19_data_analysis_platform/templates/info.html
{#Dropped#}
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
Info
{% endblock %}

{% block body_block %}
<section id="inner-title" class="inner-title">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-6">
        <h2>Information</h2>
      </div>
      <div class="col-md-6 col-lg-6">
        <div class="breadcrumbs">
          <ul>
            <li>Current Page:</li>
            <li><a href="{% url 'index' %}">Homepage</a></li>
            <li><a href="{% url 'info' %}">Info</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="section16" class="section16">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-md-offset-1">
        <div class="single-location">
          <div class="loc-icon">
            <i class="fa fa-phone fa-2x"></i>
          </div>
          <span class="loc-content">+44 752 999 7299</span>
          <span class="loc-content">+86 150 4056 9459</span>
        </div>
      </div>
      <div class="col-md-4">
        <div class="single-location">
          <div class="loc-icon">
            <i class="fa fa-envelope fa-2x"></i>
          </div>
          <span class="loc-content">wangyulinchris@gmail.com</span>
          <span class="loc-content">905946576@qq.com</span>
        </div>
      </div>
      <div class="col-md-3">
        <div class="single-location">
          <div class="loc-icon">
            <i class="fa fa-map-marker fa-2x"></i>
          </div>
          <span class="loc-content">107 Kelvinhaugh Street,</span>
          <span class="loc-content">Glasgow, G3 8PX</span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-lg-6">
        <form id="contact" role="form">
          <!-- successfully -->
          <p class="success alert alert-success"><i class="fa fa-check"></i> Your message has been sent successfully. </p>
          <!-- unsuccessfully -->
          <p class="error alert alert-danger"><i class="fa fa-times"></i> E-mail must be valid and message must be longer than 1 character. </p>
          <div class="control-group form-group">
            <div class="controls">
              <input  class="form-control" id="cf-name" type="text" name="cf-name" placeholder="NAME">
              <p class="help-block"></p>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <input class="form-control" id="cf-email" type="email" name="cf-email" placeholder="EMAIL">
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
             <input class="form-control" id="cf-subject" type="text" name="cf-subject" placeholder="SUBJECT">
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <textarea class="form-control custom-control" id="cf-message" rows="4" name="cf-message" placeholder="HOW CAN I HELP? "></textarea>
            </div>
          </div>
          <div id="success"></div>
          <!-- For success/fail messages -->
          <button type="submit" id="cf-submit" name="submit" class="btn btn-primary">SUBMIT</button>
        </form>
      </div>
      <div class="col-md-6 col-lg-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.4515050296823!2d85.30938781439113!3d27.70334258279361!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m3!3e6!4m0!4m0!5e0!3m2!1sen!2snp!4v1469920087323" width="800" height="370" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</section>

{% endblock %}